# Generated by Django 3.0 on 2024-02-22 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=30)),
                ('shop_place', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('shop_phone', models.CharField(max_length=30)),
                ('owner_name', models.CharField(default='', max_length=30)),
                ('shop_license_no', models.CharField(max_length=30)),
                ('photo', models.CharField(default='', max_length=250)),
                ('post', models.CharField(max_length=30)),
                ('pin', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('pin', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('aadhar_no', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('aadhar_no', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('pin', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=30)),
                ('photo', models.CharField(default='', max_length=250)),
                ('type', models.CharField(max_length=30)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.Login')),
                ('SHOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('Booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.Booking')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lattitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('Login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.Login')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('rent_amount', models.CharField(max_length=30)),
                ('SHOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('reply', models.CharField(max_length=30)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.User')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='DEVICE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.Device'),
        ),
        migrations.AddField(
            model_name='booking',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.User'),
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('Booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.Booking')),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.Staff')),
            ],
        ),
    ]
