# Generated by Django 3.0 on 2024-02-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='photo',
            field=models.CharField(default='', max_length=250),
        ),
    ]
