# Generated by Django 3.0 on 2024-02-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_auto_20240224_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aadhar_no',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.CharField(default='', max_length=250),
        ),
    ]
