# Generated by Django 3.0 on 2024-03-24 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_auto_20240324_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='DEVICE',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Myapp.Device'),
        ),
    ]
