# Generated by Django 3.0 on 2024-03-24 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_booking_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsub',
            name='DEVICE',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Myapp.Device'),
        ),
    ]
