from django.contrib import admin
from django.urls import path

from Myapp import views

urlpatterns = [
    path('login/', views.login),
    path('login_post/',views.login_post),
    path('admin_home/',views.admin_home),
    path('staff_home/',views.staff_home),
    path('shop_register',views.shop_register),
    path('shop_register_post/',views.shop_register_post),
    path('view_shop/',views.view_shop),
    path('view_shop_search/',views.view_shop_search),
    path('view_shop_approve/<id>',views.view_shop_approve),
    path('view_shop_reject/<id>',views.view_shop_reject),
    path('shop_home/',views.shop_home),
    path('view_approved_shop/',views.view_approved_shop),
    path('view_rejected_shop/',views.view_rejected_shop),
    path('add_staff/',views.add_staff),
    path('add_staff_post/',views.add_staff_post),
    path('view_staff/',views.view_staff),
    path('view_staff_search/',views.view_staff_search),
    path('shop_index/',views.shop_index),
    path('edit_staff/<id>',views.edit_staff),
    path('edit_staff_post/',views.edit_staff_post),
    path('delete_staff/<id>',views.delete_staff),
    path('add_device/',views.add_device),
    path('add_device_post/',views.add_device_post),
    path('view_device/',views.view_device),
    path('view_device_search/',views.view_device_search),
    path('edit_device/<id>',views.edit_device),
    path('edit_device_post/',views.edit_device_post),
    path('delete_device/<id>',views.delete_device),
    path('logout/',views.logout),
    path('user_login/',views.user_login),
    path('user_register/',views.user_register),
    path('user_view_profile/',views.user_view_profile),
    path('user_edit_profile/',views.user_edit_profile),
    path('user_view_shop/',views.user_view_shop),
    path('user_view_device/',views.user_view_device),
    path('user_order_device/',views.user_order_device),
    path('user_change_password/',views.user_change_password),
    path('staff_view_profile/',views.staff_view_profile),
    path('staff_view_profile_post/',views.staff_edit_profile_post),
    path('staff_edit_profile/',views.staff_edit_profile),
    path('staff_edit_profile_post/',views.staff_edit_profile_post),
    path('view_users/',views.view_users),
    path('view_users_post/',views.view_users_post),
    path('deliverystaff_view_profile/',views.deliverystaff_view_profile),
    path('deliverystaff_edit_profile/',views.deliverystaff_edit_profile),
    path('user_view_booking_details/',views.user_view_booking_details),
    path('shop_booking_details/',views.shop_booking_details),
    path('view_shop_bookingdetails_search/',views.view_shop_bookingdetails_search),
    path('delete_bookingdetails/<id>',views.delete_bookingdetails),
    path('deliverystaff_change_password/',views.deliverystaff_change_password),
    path('staff_payment_status/',views.staff_payment_status),
    path('view_paymentstatus_search/',views.view_paymentstatus_search),
    path('staff_booking_details/',views.staff_booking_details),
    path('view_staff_bookingdetails_search/',views.view_staff_bookingdetails_search),
    path('delete_bookingdetails/<id>',views.delete_bookingdetails_staff),
    path('assign_order/<id>',views.assign_order),
    path('update_location/',views.update_location),
    path('assign_order_post/',views.assign_order_post),
    path('view_orders_assigned/',views.view_orders_assigned),
    path('shop_profile_view/',views.shop_profile_view),
    path('shop_view_profile_post/',views.shop_view_profile_post),
    path('shop_edit_profile/',views.shop_edit_profile),
    path('shop_edit_profile_post/',views.shop_edit_profile_post),
    path('update_work_status/',views.update_work_status),
    path('view_work_status/',views.view_work_status),
    path('user_send_complaint/',views.user_send_complaint),
    path('viewcomplaint/',views.viewcomplaint),
    path('view_comlaint_post/',views.view_comlaint_post),
    path('send_reply/<id>',views.send_reply),
    path('sendreply_POST/',views.sendreply_POST),
    path('viewreply_POST/',views.viewreply_POST),
    path('user_send_feedback/',views.user_send_feedback),
    path('view_feedback/',views.view_feedback),
    path('view_feedback_post/',views.view_feedback_post),
    path('view_deliverystaff_assigned/<id>',views.view_deliverystaff_assigned),


]